CREATE TABLE `fact_workflow_snapshots`
(
    `id`                             bigint unsigned                                               NOT NULL AUTO_INCREMENT,
    `n8n_execution`                  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `n8n_subflow`                    varchar(255)                                                           DEFAULT NULL,
    `dim_version_id`                 int unsigned                                                  NOT NULL,
    `config_import_dim_stage_id`     int unsigned                                                           DEFAULT NULL,
    `config_import_dim_status_id`    int unsigned                                                           DEFAULT NULL,
    `config_import_start_timestamp`  timestamp                                                     NULL     DEFAULT NULL,
    `config_import_end_timestamp`    timestamp                                                     NULL     DEFAULT NULL,
    `folder_search_dim_stage_id`     int unsigned                                                           DEFAULT NULL,
    `folder_search_dim_status_id`    int unsigned                                                           DEFAULT NULL,
    `folder_search_start_timestamp`  timestamp                                                     NULL     DEFAULT NULL,
    `folder_search_end_timestamp`    timestamp                                                     NULL     DEFAULT NULL,
    `file_search_dim_stage_id`       int unsigned                                                           DEFAULT NULL,
    `file_search_dim_status_id`      int unsigned                                                           DEFAULT NULL,
    `file_search_start_timestamp`    timestamp                                                     NULL     DEFAULT NULL,
    `file_search_end_timestamp`      timestamp                                                     NULL     DEFAULT NULL,
    `batch_manifest_dim_stage_id`    int unsigned                                                           DEFAULT NULL,
    `batch_manifest_dim_status_id`   int unsigned                                                           DEFAULT NULL,
    `batch_manifest_start_timestamp` timestamp                                                     NULL     DEFAULT NULL,
    `batch_manifest_end_timestamp`   timestamp                                                     NULL     DEFAULT NULL,
    `batch_creation_dim_stage_id`    int unsigned                                                           DEFAULT NULL,
    `batch_creation_dim_status_id`   int unsigned                                                           DEFAULT NULL,
    `batch_creation_start_timestamp` timestamp                                                     NULL     DEFAULT NULL,
    `batch_creation_end_timestamp`   timestamp                                                     NULL     DEFAULT NULL,
    `total_files_processed`          int unsigned                                                  NOT NULL DEFAULT '0',
    `total_batches_created`          int unsigned                                                  NOT NULL DEFAULT '0',
    `total_bytes_processed`          bigint unsigned                                               NOT NULL DEFAULT '0',
    `error_count`                    int unsigned                                                  NOT NULL DEFAULT '0',
    `created_at`                     timestamp                                                     NULL     DEFAULT CURRENT_TIMESTAMP,
    `updated_at`                     timestamp                                                     NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `dim_version_id` (`dim_version_id`),
    KEY `config_import_dim_stage_id` (`config_import_dim_stage_id`),
    KEY `config_import_dim_status_id` (`config_import_dim_status_id`),
    KEY `folder_search_dim_stage_id` (`folder_search_dim_stage_id`),
    KEY `folder_search_dim_status_id` (`folder_search_dim_status_id`),
    KEY `file_search_dim_stage_id` (`file_search_dim_stage_id`),
    KEY `file_search_dim_status_id` (`file_search_dim_status_id`),
    KEY `batch_manifest_dim_stage_id` (`batch_manifest_dim_stage_id`),
    KEY `batch_manifest_dim_status_id` (`batch_manifest_dim_status_id`),
    KEY `batch_creation_dim_stage_id` (`batch_creation_dim_stage_id`),
    KEY `batch_creation_dim_status_id` (`batch_creation_dim_status_id`),
    KEY `n8n_execution` (`n8n_execution`),
    KEY `n8n_subflow` (`n8n_subflow`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_1` FOREIGN KEY (`dim_version_id`) REFERENCES `dim_versions` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_10` FOREIGN KEY (`batch_creation_dim_stage_id`) REFERENCES `dim_stages` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_11` FOREIGN KEY (`batch_creation_dim_status_id`) REFERENCES `dim_statuses` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_2` FOREIGN KEY (`config_import_dim_stage_id`) REFERENCES `dim_stages` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_3` FOREIGN KEY (`config_import_dim_status_id`) REFERENCES `dim_statuses` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_4` FOREIGN KEY (`folder_search_dim_stage_id`) REFERENCES `dim_stages` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_5` FOREIGN KEY (`folder_search_dim_status_id`) REFERENCES `dim_statuses` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_6` FOREIGN KEY (`file_search_dim_stage_id`) REFERENCES `dim_stages` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_7` FOREIGN KEY (`file_search_dim_status_id`) REFERENCES `dim_statuses` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_8` FOREIGN KEY (`batch_manifest_dim_stage_id`) REFERENCES `dim_stages` (`id`),
    CONSTRAINT `fact_workflow_snapshots_ibfk_9` FOREIGN KEY (`batch_manifest_dim_status_id`) REFERENCES `dim_statuses` (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
